apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
# type: ClusterIP             # ðŸ‘ˆ CHANGED FROM ClusterIP TO NodePort  is dont wnat to expose outside
  selector:
    app: auth
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32405   # ðŸ‘ˆ FIXED PORT